name = "blog"
compatibility_date = "2024-07-15"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMmI4MjIzMGEtYmY4ZS00ZGE5LWI0ZDYtZjc2Y2VjNWZlYTU0IiwidGVuYW50X2lkIjoiMmE4ZDg0YmJmZGFkNjViNGNlNzVmMDE3YjM5OTM4NzY5NGM5ZTgzZGQ1Zjg1NzQ0NWJmNGYwZTA3YWIxNGJhMiIsImludGVybmFsX3NlY3JldCI6IjY5NTEwNDg1LTE1ZDUtNGY4Mi1hYWRhLTZhYjM0YzZhZWViMiJ9.6BgzOz7GwGa9_UEQT6p33p0Rkvg6sqzxFs4BbZO5ErE"
JWT_SECRET = "hrudayvvsecret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"